### ISSUE TITLE
Zwracanie listy restauracji

### ISSUE THREAD

**Issue by Faktura179** [Backend-WSEI-Frontczak-zaliczenie/projekt-zaliczeniowy#1]
Trzeba dodać repozytorium w infrastrukturze, pozwalające na pobranie listy restauracji z endpointa w web. Jako klasę dto można zrobić RestaurantRecord w Web

**Comment by mikord45** [comment]
https://github.com/Backend-WSEI-Frontczak-zaliczenie/projekt-zaliczeniowy/pull/7
