### ISSUE TITLE
Admin - usuwanie i edytowanie komentarzy 

### ISSUE THREAD

**Issue by Faktura179** [Backend-WSEI-Frontczak-zaliczenie/projekt-zaliczeniowy#6]
Do tego jest potrzebny serwis w Core, w którym następuje walidacja poprawności wprowadzonych danych.
W fastendpointach dodać trzeba dodać ` Roles("Admin");` żeby weryfikowało czy użytkownik ma rolę admina.

**Comment by przemyslawmatraj** [comment]
#13
